### ISSUE TITLE
Importing UFF58 does not create a new model

### ISSUE THREAD

**Issue by sbtlaarzc** [openmodal/OpenModal#15]
If I want to import a UFF58 file it does not create a new model.

The catch is obviously in the missing UFF151 dataset and UFF164. When they are present, the program works as expected.

**Comment by matmr** [comment]
@sbtlaarzc the .uff file would help 🤙

**Comment by jankoslavic** [comment]
Should we implement default UFF151 and UFF164 in pyuff?

**Comment by matmr** [comment]
Here it is. Test pls 🌵 

@jankoslavic The absence of fields tricked the openmodal internal data model. In my opinion it was a problem of import script and not a problem of the pyuff library. Unless you had something else in mind?

**Comment by jankoslavic** [comment]
@sbtlaarzc can you please test it? I currently do not have a working environment:(

**Comment by matmr** [comment]
I tested with 1 file and it worked but I know blaz has more data :)

**Comment by sbtlaarzc** [comment]
This is the file (note I saved it as .txt, since GitHub does not support uploading a .uff - please change manually):
[measurement.txt](https://github.com/openmodal/OpenModal/files/825766/measurement.txt)

**Comment by sbtlaarzc** [comment]
@matmr  I tested it now and it works, however I have one more recomendation:
- The default model name is currently Model-1. I recommend that the model is named after `Response Entity Name` or `Reference Entity Name` (in most cases they are the same).

**Comment by matmr** [comment]
Seeing that this entity name is widely considered relevant, I agree.

Will you try to add this feature? Passing the torch 🔥 😄
