### ISSUE TITLE
BUG: `measurement_id` in `measurement_values_td` mdd file not working properly

### ISSUE THREAD

**Issue by sbtlaarzc** [openmodal/OpenModal#19]
When doing ODS measurements and saving time history, I noticed a bug in the `measurement_values_td` table (in the mdd file): The `measurement_id` is not updated accordingly to other tables (`measurement_index` and `measurement_values`). The value is always `1`.

**Comment by matmr** [comment]
This is a major bug. It is on the top of my list :)

**Comment by sbtlaarzc** [comment]
Issue resolved (not actually an issue). This was my mistake while coding (overwritten a parameter).
