### ISSUE TITLE
Coding issue

### ISSUE THREAD

**Issue by mantielero** [openmodal/OpenModal#25]
When I try to install in Linux it complains about:
`$ python2 setup.py install
  File "setup.py", line 2
SyntaxError: Non-ASCII character '\xc5' in file setup.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`
This could be solved by adding to **setup.py**:
`#!-*-coding:utf-8 -*-`

Regards,
Jose Maria

**Comment by jankoslavic** [comment]
Dear Jose!
Thank yuo for the open issue and the solution. It looks like you are using py2. In this case, I guess all py files  should have the #!-*-coding:utf-8 -*- header. Can you confirm this?

**Comment by mantielero** [comment]
That problem should take place in both Python2 and python3 (but I haven't tried it).  That's right, all files should have that header. More info [here](https://www.python.org/dev/peps/pep-0263/).

**Comment by matmr** [comment]
Mantielero!

As of right now your best way of running openmodal is cloning the branch 'ubuntu-linux-tested', installing requirements.txt with pip within a virtualenv and running
```
python openmodal.py
```

It's best to have python3, which is what we use.

The setup.py was primarily used for doing cx_freeze within a special environment, to distribute to users. It ~~should~~ will be upgraded and improved.
