### ISSUE TITLE
Running openmodal on linux

### ISSUE THREAD

**Issue by raphaeltimbo** [openmodal/OpenModal#27]
I am trying to use openmodal on a linux machine but I am having some problems.
First I tried to set a virtual machine with a windows 10 guest and start openmodal from there. 
I have enabled 3d acceleration in the virtual machine and Openmodal is starting, but when I try to load an .uff file I get an error saying that my OpenGL is 1.1.0 and pyqtgraph requires 2.0 or greater. 
For me it was not so trivial to update the opengl in the virtual machine. Any thoughts on that?
Currently I am using virtualbox, maybe I should try with vmware...

I have also tried to run directly on linux, but had some problems trying to install PyQt4. 
Currently I have python 3.6 installed. Does openmodal need an specific python version?

**Comment by matmr** [comment]
Hi Raphael!

I'm running a Linux machine at home now so you can expect it to be better supported in the future. I am running a Ubuntu based distro and have managed to run the software. But yes, there were some problems with pyqt4, as you can not get it with pip. Here's what I propose:

- Install python3, create a virtualenv and activate it
- Checkout branch 'ubuntu-linux-tested' and install requirements
    ```
    >>> pip install -r requirements.txt
    ```
- Run openmodal.

This will install openmodal with pyqt5, which can be done nicely with pip.

Btw: Yes, VirtualBox could be the reason for the opengl errors. Try different settings for 2D and 3D acceleration.

Let me know if you still experience trouble or if you need help with any of the above steps. I can only confirm it will launch the app so far, will be testing different features in the following days.


Take care,
mm

**Comment by raphaeltimbo** [comment]
Thanks Matjaž!
I was able to launch the app on linux! I have tried to import the beam.uff file available in pyuff/data just to test the installation but I am getting an error:

```
Traceback (most recent call last):
  File "/home/raphael/OpenModal-ubuntu-linux-tested/OpenModal/gui/skeleton.py", line 968, in run
    self.modaldata_object.import_uff(self.file_name)
  File "../OpenModal/modaldata.py", line 386, in import_uff
    uffdata = ModalDataUff(fname, base_key=base_key)
  File "../OpenModal/modaldata.py", line 644, in __init__
    self.create_model()
  File "../OpenModal/modaldata.py", line 673, in create_model
    self.populate_model(model_id+self.base_key, model)
  File "../OpenModal/modaldata.py", line 684, in populate_model
    self.gen_geometry_table(model_id, model)
  File "../OpenModal/modaldata.py", line 875, in gen_geometry_table
    cspresent = self.getlocalcs(model_id, model)
  File "../OpenModal/modaldata.py", line 805, in getlocalcs
    leu['thx'] = np.asarray(thx)*180./np.pi
  File "/home/raphael/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2331, in __setitem__
    self._set_item(key, value)
  File "/home/raphael/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2397, in _set_item
    value = self._sanitize_column(key, value)
  File "/home/raphael/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2568, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "/home/raphael/anaconda3/lib/python3.6/site-packages/pandas/core/series.py", line 2879, in _sanitize_index
    raise ValueError('Length of values does not match length of ' 'index')
ValueError: Length of values does not match length of index
Aborted (core dumped)

```

**Comment by matmr** [comment]
Thanks for the error report.

There are still some problems with reading uff files we have to sort out. The problem is that outputs from different software packages can vary slightly.

You should be able to open measurement.uff but most of other files cause errors.

Will get to this when there's time.

In the meanwhile ... do you plan to open any specific uff files, as in what software will you use to export/generate uff files?

**Comment by raphaeltimbo** [comment]
I wanted to export uff files from the artemis software.
I have now updated the pyuff copy that I have and tried to load the measurement.uff file. 
It is showing the following error:

```
Traceback (most recent call last):
  File "/home/raphael/OpenModal/OpenModal/gui/skeleton.py", line 956, in endimport
    widget.reload()
  File "../OpenModal/gui/widgets/animation.py", line 838, in reload
    self.build_uff_tree(self.modaldata,refresh=refresh)
  File "../OpenModal/gui/widgets/animation.py", line 787, in build_uff_tree
    on_activate(self.preferences['selected_model_id'])
  File "../OpenModal/gui/widgets/animation.py", line 728, in on_activate
    self.plot_activated_models()
  File "../OpenModal/anim_tools.py", line 1145, in plot_activated_models
    self.manage_gcs_plot()
  File "../OpenModal/anim_tools.py", line 1122, in manage_gcs_plot
    gcs_scale = dist * 0.03 * 2 / window_width_ratio
ZeroDivisionError: float division by zero
Aborted (core dumped)
```

**Comment by matmr** [comment]
Are you running the latest ubuntu-linux-tested branch of openmodal?

It imports fine on my side. Maybe @miha-pirnat can shed some light on this error.

I'll try to have a look but please confirm for me that you are running the correct branch.

**Comment by raphaeltimbo** [comment]
I confirm the branch is up to date:

```
(openmodal) raphael@raphael:~/OpenModal$ git status
On branch ubuntu-linux-tested
Your branch is up-to-date with 'origin/ubuntu-linux-tested'.
nothing to commit, working directory clean
(openmodal) raphael@raphael:~/OpenModal$ git pull
Already up-to-date.
```

**Comment by matmr** [comment]
Yep. Looks like it's supposed to!

Since we have trouble getting same results with this file, I believe it would help if we could have another benchmark file. I'm note sure if you've shared any files with us yet (please remind me if you did) ... but if you are able to share an example file (from artemis software?) I could probably look at it and iron out the kinks for you.

There's no need for it to contain any serious (or potentially sensitive) data, but it's important that all the fields, that are usually there, are represented and filled with data that makes sense.

I'm kind of swamped at the moment but will get back to you as soon as there's time.

**Comment by raphaeltimbo** [comment]
I have shared the files that are in the pyuff package (Artemis export - Geometry RPBC... and Artemis export - data...). Sorry for the late response.

**Comment by matmr** [comment]
I checked the files. One of them is binary (field 58) and crashes in pyuff on decode. Personally don't have much experience with binary fields but will take a look. Might have to do with encoding and such.

The second one has an elements field (2412), which I'm not sure if we support. But there are also trouble with reading numbers, due to the specific formatting.

I'll try to resolve some of this errors but it will take some time.

Also this issue should at some point be moved to pyuff ...

**Comment by jankoslavic** [comment]
@matmr binary should work fine, also the 2412. is OM using the latest version of pyuff?

**Comment by matmr** [comment]
OpenModal should use the latest version from pip ...

Will check opening just with the pyuff library when I find the time.

**Comment by averter** [comment]
Hi,
Using python 3.8.10 and pip 21.3.1 on linux mint in a virtualenv I am getting this error
````
ERROR: Could not find a version that satisfies the requirement sip==4.19.3 (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0, 5.4.0, 5.5.0, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.1.0, 6.1.1, 6.2.0, 6.3.0, 6.3.1, 6.4.0)
ERROR: No matching distribution found for sip==4.19.3
````
I have tried to use python 3.6.10 instead but the result was even worse (failed much sooner) when trying to install `PyDAQmx==1.3.2`. Thank you in advance for any help and looking forward to work with/collaborate in this awesome project

**Comment by jankoslavic** [comment]
Dear @averter thank you for your comment; OM is not actively developed. I would suggest checking out pyEMA (https://github.com/ladisk/pyEMA). Kind regards, Janko
