### ISSUE TITLE
BUG: exe cannot read measurement.uff

### ISSUE THREAD

**Issue by jankoslavic** [openmodal/OpenModal#28]
If I generate a measurement file with the pyuff as shown in the showcase notebook:
https://github.com/openmodal/pyuff/tree/master/

I cannot import it to OM!

**Comment by matmr** [comment]
So far I traced the problem to here:
https://github.com/openmodal/OpenModal/blob/master/OpenModal/utils.py#L75

numpy.unique does a sort behind the scenes. It can not sort complex values.

I will try to hack this a different way, but would appreciate guidance from the authors (@sbtlaarzc @miha-pirnat). Why unique indices here and do we need the sort? Can we sort by absolute values?

**Comment by matmr** [comment]
Also, commenting out this line:
https://github.com/openmodal/OpenModal/blob/master/OpenModal/gui/widgets/animation.py#L2109

doesn't seem to break anything but everything seems to work. Please test on linux branch and let me know how it's working for you.

Have some more digging to do ...

**Comment by sbtlaarzc** [comment]
@matmr , the problem with `numpy.unique`, since the input type is `dtype=object`. If the type is changed to `dtype=complex` the code works.

This has already been addressed in commits https://github.com/openmodal/OpenModal/commit/710d78776b6e8047ee84f82f0c708230ae3c68be and https://github.com/openmodal/OpenModal/commit/988b5cbd605aaa16f6a62798d52d82110219e0d3

**Comment by matmr** [comment]
Thanks Blaz! Will carry this change over shortly.

Now just need the conformation from @miha-pirnat 

And maybe a test with one or two uff files :)

**Comment by matmr** [comment]
@jankoslavic I did some tests and practically all of the .uffs in the pyuff/data folder crash openmodal. Is anyone working on this?

**Comment by jankoslavic** [comment]
@matmr I was working on this a while ago, as far as I could figure out is not the issue of importing uff, but handling of the GUI (deactivation/activation of the models).

**Comment by matmr** [comment]
Did these work at any point in the past? Where are the uffs that worked? Trying to pinpoint if it's the format. Because the formatting can vary and can be very problematic.

**Comment by jankoslavic** [comment]
@sbtlaarzc if I remember correctly you have been testing UFF import/export and it was working... is this right?

**Comment by sbtlaarzc** [comment]
I checked yesterday. Importing only dataset 58 works. However, the import is not working, when other datasets are present, i.e. see beam.uff in the pyuff examples.

**Comment by matmr** [comment]
We had a stash of these files that we used in the past to test. I think these were not the same as the files in the pyuff repo.

Anyone has them handy?
