### ISSUE TITLE
Panning does not work

### ISSUE THREAD

**Issue by sgrobler** [openmodal/OpenModal#32]
Hi
I'm unable to pan my geometry. My mouse has a wheel so I understand I should be able to pan by holding the wheel-button in and moving the mouse, but it does not work. I can rotate teh model using the left button and I can zoom using the wheel, just not pan.
I am using Windows 7 professional. Any tips?

Regards
Steve

**Comment by miha-pirnat** [comment]
Hello Steve,
current implementation of panning has a ''singularity'' issue when Z-axis is perpendicular to screen surface.  Try rotating the model before panning...it should work.
Best regards,
Miha

**Comment by sgrobler** [comment]
OK, I found the problem - in my mouse setup the wheel-button was set to "double click". When I change it to "middle-click" it works fine!
Steve
