### ISSUE TITLE
import uff - where is the data?

### ISSUE THREAD

**Issue by sgrobler** [openmodal/OpenModal#33]
Hi all
I've got .unv file that I created in matlab. It contains 16 channels of acceleration time-history. After its finished loading, where do I go to view the time histories? I want to do an OMA on the data. 
regards
Steve

**Comment by miha-pirnat** [comment]
Hello,
after import you can view imported data in the 'measurements', 'analysis' and 'animation' tabs. OMA is not implemented in openmodal, however, typical modal analysis is (use analysis tab). 
You can still directly animate your data and get some insights this way, but this is far from operational modal analysis.

**Comment by sgrobler** [comment]
I've tried importing a .unv with time history and a .unv that I think contains FRF's. In both cases there is nothing to see when I go to measurement, analysis or animation tabs. Does anyone have a sample .unv (type 58) I can try? 

Sorry to hear that there is no OMA - that's what I was really interested in!

**Comment by miha-pirnat** [comment]
You can find test data here:
https://github.com/openmodal/pyuff/tree/master/tests

You will still be able to animate deflection shapes and get natural frequencies. You will also be able to use analysis tools in openmodal, however, you will need to be aware that your FRFs are not scaled to some known input.

**Comment by sgrobler** [comment]
Thanks for the reply - I've been away for last couple of weeks but I tried finding these files tonight. 

I found "Sample_UFF58_ascii.uff" and downloaded it. The header says this is a pressure-time signal. I tried to load it in openModal using "import uff" from the menu. The status shows "importing" then "ready". When I go to the Measurement or Analysis or Animation menus there is still nothing shown - can anyone give me a step-by-step instruction on how to view  Sample_UFF58_ascii.uff?
regards
Steve

**Comment by miha-pirnat** [comment]
Uff file needs to have info fields at the begining of the file in order to be read correctly. Try data from:
https://github.com/openmodal/pyuff/tree/master/tests

An example info fields (spacing is important!):

```
    -1
   151                                                                          
NewModelx                                                                        
DefaultDecription                                                               
modaldata v1                                                                    
28-okt-17 10:10:22           0         0         0
28-okt-17 10:10:22  
Open Modal                                                                      
28-okt-17 10:10:22  
    -1
    -1
   164                                                                          
         9    User unit system         1
   1.0000000000000000D+00   1.0000000000000000D+00   1.0000000000000000D+00
   1.0000000000000000D+00
    -1
```

**Comment by sgrobler** [comment]
Hi, I've been away for a while but back now and trying to load some data. Still not working.
I want to load a time-history file which I think would be a UFF58 file? The one I downloaded from the link you mentioned looks like this:

   _-1
    58
Mic 01.0Scalar
NONE
18-Apr-16 13:49:58
NONE
NONE
    1         0    0         0 Mic 01             0   1 NONE               0   0
         2     79292         1  0.00000E+00  1.52588E-05  0.00000E+00
        17    0    0    0 time                 s                   
        21    0    0    0 Pressure             Pa                  
         0    0    0    0 NONE                 NONE                
         0    0    0    0 NONE                 NONE                
 -1.47553E-02 -1.72957E-02 -1.66101E-02 -1.61988E-02 -1.68925E-02 -1.53669E-02
 -1.44522E-02 -1.56589E-02 -1.65244E-02 -1.59448E-02 -1.54754E-02 -1.55387E-02_

When I load it, I see nothing in any of the tabs in openModal. Can anyone post me a file that is known to work? 
Thanks - Steve
