### ISSUE TITLE
Animate modes

### ISSUE THREAD

**Issue by mgx4** [openmodal/OpenModal#35]
Good morning,
I imported a .uff file containing FRF from Experimental Modal Analysis (EMA). I generated the mesh (geometry) of the tested structure with lines and triangle surfaces. I succeed to realize the analysis and extract eigen frequencies and modal damping. What I am still unable to do is to animate the geometry according to eigen shapes as a function of eigen frequencies. When I am on the tab "Measurement" on the tab menu "ANIMATION" and I put the frequency cursor on one peak of the FRF and I click on "Play", I can just see one node moving. I would like to observe all the nodes moving in order to identify the eigen shape of the mode observed. Do you please have an idea on how to do that? Thank you for your help!

**Comment by miha-pirnat** [comment]
Hello,

in animation tab try a right click on model and under "roving type" select
"response roved".

Miha

24. nov. 2017 09:40 je oseba "mgx4" <notifications@github.com> napisala:

**Comment by mgx4** [comment]
Thanks a lot!

**Comment by jankoslavic** [comment]
I added this to stack:
https://stackoverflow.com/questions/47469591/animating-modes-in-openmodal-roving-type/47469592#47469592
please give it an check mark:)
