### ISSUE TITLE
osX and Linux support for NI hardware

### ISSUE THREAD

**Issue by kevindekemele** [openmodal/OpenModal#38]
Hello, 

I would like to know if NI hardware is supported on OSX and Linux.

Kevin

**Comment by jankoslavic** [comment]
dear @kevindekemele this is more a question for NI. short answer is yes, but only base hardware is supported.

Linux: http://www.ni.com/product-documentation/11787/en/
Mac OS: http://sine.ni.com/nips/cds/view/p/lang/sl/nid/14480
