### ISSUE TITLE
failed to open alpha version openmodal software

### ISSUE THREAD

**Issue by SanthoshKumarArroju** [openmodal/OpenModal#39]
Dear all,
when I tried to Run openModal.exe, its saying "python35.dll" file is missing. But, this file is already in the downloaded package files.

Is there any alternative procedure to RUN the alpha version or Am I doing anything wrong

my system configuration: win7, 64bit and I have installed Anconda python software

![alpha version](https://user-images.githubusercontent.com/31964108/35416063-cde5eb2a-01f5-11e8-8ea0-dc2229d8facf.jpg)
![image 2](https://user-images.githubusercontent.com/31964108/35416076-dad712aa-01f5-11e8-9d1e-6c2c47a5f436.jpg)

**Comment by miha-pirnat** [comment]
You need to unzip all the files first and only then run openmodal.exe ...then it will work.

**Comment by SanthoshKumarArroju** [comment]
Dear Miha,

Thank you, I got it


Regards,
Santhosh

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by miha-pirnat** [comment]
No problem, glad I could help.
