### ISSUE TITLE
stabilisation.py: Calculation of time sampling interval

### ISSUE THREAD

**Issue by QuarQuarQ** [openmodal/OpenModal#40]
The number of discrete frequencies `nf` should be calculated as follows:
`2*(len(f)-1)` instead of `2*(len(f)-low_lim-1)`, as it is implemented now. The reason is that the time sampling interval, with which the signal was measured, does not change when a lower limit of the frequency (`low_lim`) is selected for the LSCF post processing.
I attached two stabilisation diagrams from the output of the `test_stabilisation()` function with a lower limit of 1000 Hz (`low_lim=1001`). The first shows the output of the current implementation, while the second illustrates the output of my suggested correction.
![current_low_lim_1001](https://user-images.githubusercontent.com/40766163/42171091-aeaabe62-7e18-11e8-85d1-e4de11124ea5.png)
![corrected_low_lim_1001](https://user-images.githubusercontent.com/40766163/42171125-c42e6af4-7e18-11e8-936c-03a2f7db2b9a.png)
The first result yields wrong stable eigenfrequencies, while the second still yields the correct ones. The third figure shows the output with no lower frequency limit (`low_lim = 0`).
![current_low_lim_0](https://user-images.githubusercontent.com/40766163/42171137-cda71b76-7e18-11e8-88ea-00fa2cd2c3a9.png)

**Comment by jankoslavic** [comment]
Can you please share your code? E.g. on gist.github.com

**Comment by QuarQuarQ** [comment]
Thank you for your quick reply. I attached a small snippet of the relevant code where I deleted the "low_lim" subtraction. The rest of the file is untouched. These code lines refer to the line 266-277 in the source code in OpenModal/analysis/stabilisation.py.
```python
low_lim = 0
nf = (2*(len(f)-1))
print(nf)
while max(prime_factors(nf)) > 5:
    f = f[:-1]
    frf = frf[:, :-1]
    nf = (2*(len(f)-1))
print(nf)

df = (f[1] - f[0])
nf = 2*(len(f)-1)
ts = 1 / (nf * df)  # sampling period
```
Let me know if this is not enough.

**Comment by jankoslavic** [comment]
Thanks. Will look into details later today

**Comment by jankoslavic** [comment]
I agree with your comment, but have you observed this only in the helping function `test_stabilisation` (this was / is used for development only)?

I see something similar in `test_lsfd` which is again a helping function.

@QuarQuarQ have you observed the above problem in GUI?

**Comment by sbtlaarzc** [comment]
@QuarQuarQ you are right, this was a bug. I fixed it now.

The bug however is only in the testing function `test_stabilisation()` (also `test_lsfd()`) and not in the GUI (@jankoslavic ).

**Comment by jankoslavic** [comment]
Great! thank you for double check.
