### ISSUE TITLE
GANTNER_INSTRUMENTS

### ISSUE THREAD

**Issue by MisureMeccaniche** [openmodal/OpenModal#44]
Hi Miha,
are you already in contact with GANTNER INSTRUMENTS to add their hardware on your acquisition capabilities, together with NI?
https://www.gantner-instruments.com/
They provide free drivers and example for several Language and the hardware is working very well on dynamic analysis on structure (like bridge and tower).
Kind regards.

**Comment by miha-pirnat** [comment]
Hello,
no we are not in contact with them. Currently only NI hardware is supported, however, if you are willing to add support yourself, we will help you.
Best regards

**Comment by MisureMeccaniche** [comment]
Hi Miha,
yes, I'm interesting on it.
Which software Language do you use to develop Openmodal?
I can send you driver and example on how to acquire.
Kind regards.

**Comment by MisureMeccaniche** [comment]
Hi Miha,
take a look at attachment: it come from GANTNER INSTRUMENTS directly for Python.
The idea of dll is to read data from buffer internally to the controller.
Is it enough?

Kind regards.

Massimo Nannizzi
Amministratore

Misure Meccaniche srl
Sede Operativa                    Sede Legale
Via Sant’Agostino, 210      Via Oratoio, 13
56121 PISA (PI)                     56121 PISA (PI)
Tel (+39) 05029315
FAX (+39) 050984126
Mobile (+39) 3487031064
m.nannizzi@misuremeccaniche.it<mailto:m.nannizzi@misuremeccaniche.it>
https://www.misuremeccaniche.it/

***************************************************

PRIVACY

CONFIDENZIALE - In ottemperanza del D.Lgs. 30 Giugno 2003 n.196 sulla tutela dei dati personali, le informazioni contenute in questo messaggio sono strettamente riservate e sono esclusivamente indirizzate al destinatario indicato (oppure alla persona responsabile di rimetterlo al destinatario), tenendo presente che qualsiasi uso, riproduzione o divulgazione di questo messaggio è vietata.
Nel caso in cui aveste ricevuto questa mail per errore, vogliate avvertire il mittente al più presto a mezzo posta elettronica e distruggere il presente messaggio.
CONFIDENTIALITY - The  information in this e-mail and any attachments is confidential. If you are not  the recipient please notify the sender immediately and do not disclose to  another person or takes copies. Thank you.

Da: miha-pirnat <notifications@github.com>
Inviato: giovedì 27 dicembre 2018 14:28
A: openmodal/OpenModal <OpenModal@noreply.github.com>
Cc: Massimo Nannizzi <m.nannizzi@misuremeccaniche.it>; Author <author@noreply.github.com>
Oggetto: Re: [openmodal/OpenModal] GANTNER_INSTRUMENTS (#44)


Openmodal is written in python. I'm affraid that sending driver will not be enough, you should write python code yourself and then we would merge it into openmodal master branch via github.

**Comment by miha-pirnat** [comment]
I don't see any attachment?

**Comment by MisureMeccaniche** [comment]
Hi Miha,
I sent attachment, probably your antivirus remove it: it is a .zip file.
Try again attached to this email and copy also info@openmodal.com.

Kind regards.

Massimo Nannizzi
Amministratore

Misure Meccaniche srl
Sede Operativa                    Sede Legale
Via Sant’Agostino, 210      Via Oratoio, 13
56121 PISA (PI)                     56121 PISA (PI)
Tel (+39) 05029315
FAX (+39) 050984126
Mobile (+39) 3487031064
m.nannizzi@misuremeccaniche.it<mailto:m.nannizzi@misuremeccaniche.it>
https://www.misuremeccaniche.it/

***************************************************

PRIVACY

CONFIDENZIALE - In ottemperanza del D.Lgs. 30 Giugno 2003 n.196 sulla tutela dei dati personali, le informazioni contenute in questo messaggio sono strettamente riservate e sono esclusivamente indirizzate al destinatario indicato (oppure alla persona responsabile di rimetterlo al destinatario), tenendo presente che qualsiasi uso, riproduzione o divulgazione di questo messaggio è vietata.
Nel caso in cui aveste ricevuto questa mail per errore, vogliate avvertire il mittente al più presto a mezzo posta elettronica e distruggere il presente messaggio.
CONFIDENTIALITY - The  information in this e-mail and any attachments is confidential. If you are not  the recipient please notify the sender immediately and do not disclose to  another person or takes copies. Thank you.

Da: miha-pirnat <notifications@github.com>
Inviato: martedì 5 febbraio 2019 18:24
A: openmodal/OpenModal <OpenModal@noreply.github.com>
Cc: Massimo Nannizzi <m.nannizzi@misuremeccaniche.it>; Author <author@noreply.github.com>
Oggetto: Re: [openmodal/OpenModal] GANTNER_INSTRUMENTS (#44)


I don't see any attachment?

**Comment by miha-pirnat** [comment]
Thank you for sharing this, however it seems quite a lot of time would be needed to make this work and then also to test it. I think it is not possible for us to do it at this time as we all have our full time jobs. You are welcome to try yourself.
